### ISSUE TITLE
Nesting Popup in DivIcon

### ISSUE THREAD

**Issue by seanes** [jgimbel/react-leaflet-div-icon#2]
As far as I can see, DivIcon currently does not nesting react-leaflet Popup as a child, like e.g.

```
<Marker
 ...
>
 <Popup>
</Popup>
</Marker>
```

Will this be supported for DivIcon, or is it possible today?  Is there a workaround to include or add popup to DivIcon?

**Comment by steezeburger** [comment]
Hey seanes, I just made a PR that supports this here https://github.com/jgimbel/react-leaflet-div-icon/pull/5
