### ISSUE TITLE
Markers move on zoom

### ISSUE THREAD

**Issue by prh7** [jgimbel/react-leaflet-div-icon#9]
I have a issue with the markers. The issue is that the position of the markers are not fixed and changes its position on different zoom levels.

This link [http://stackoverflow.com/questions/17875438/leafletjs-markers-move-on-zoom](url) suggests some answer. But, it implies for leaflet icon but not for leaflet divicon. 

Do we have same solution like in the above link for this plugin?

**Comment by mbalabash** [comment]
Just add the same option to your divIconComponent. 
For example my marker icon has size 30x37:
`<MapMarker customIcon={iconImg} iconAnchor={[30, 37]} position={mapPosition} />`

Where MapMarker is (just for example): 
`const MapMarker = ({ customIcon, ...props }) => (`
`<DivIcon {...props}>`
`    <CustomIconWrapper>{customIcon}</CustomIconWrapper>`
 `   <Marker />`
`  </DivIcon>`
`);`
